name: "Publish to GitHub Packages"
on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish-to-gh-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        working-directory: cool_library
        run: sbt publish



